### ISSUE TITLE
有描边的时候，隐约可以看到白色间隙，但是不明显

### ISSUE THREAD

**Issue by LLQQHH** [csdn-mobile/RoundView#3]
![image](https://user-images.githubusercontent.com/19651932/138022967-fb32425c-8ba8-49e5-83e2-81d8d7f4d48d.png)

**Comment by KuangGang** [comment]
8.0？

**Comment by LLQQHH** [comment]
刚才这个是小问题，在5.1手机上测试变成这样了，但是你的RoundConCorners旧项目不会！建议发布新版本前，用Android自带的模拟器测试一下，Android5.1，Android8.0，Android10。没问题再发布
![image](https://user-images.githubusercontent.com/19651932/138027876-4f408671-2808-4a83-82f9-35843e579c30.png)

**Comment by KuangGang** [comment]
收到

**Comment by KuangGang** [comment]
您好我这里测试5.1模拟器，API 22 没有问题呀

**Comment by LLQQHH** [comment]
你好，我是下载你的demo，用Android studio 自带的5.1模拟器，API 22 ！就出现我截图的那个问题，新版本就是8.0黑边，5.2就如上图！你没问题是不是运行了你修改后的代码而不是GitHub下载的demo，你下载GitHub的demo运行就能发现问题了

**Comment by KuangGang** [comment]
那辛苦您下载一下源码运行一下看会有问题吗？

**Comment by LLQQHH** [comment]
你几个小时前又更新了一版，我没看到，我现在下载看看会不会有问题

**Comment by LLQQHH** [comment]
demo下载没有问题！

**Comment by LLQQHH** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="#0000FF" android:state_pressed="true"/>
    <item android:color="#00FF00" android:state_selected="true"/>
    <item android:color="@color/colorAccent" android:state_selected="false"/>
</selector>`
pressed颜色无法触发，大概原因是press的时候无法触发draw(Canvas canvas)方法

**Comment by KuangGang** [comment]
收到，我们试一下

**Comment by KuangGang** [comment]
先用selected状态哈
